config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #root "static_page#home"
  #root "sites#home"
  root "posts#index"
  # root to: "static_page#home"  # 上記はこれの省略形

  get "/about", to: "static_page#about"
  get "/team", to: "static_page#team"
  get "/testimonials", to: "static_page#testimonials"
  get "/services", to: "static_page#services"
  get "/portfolio", to: "static_page#portfolio"
  get "/portfolio-details", to: "static_page#portfolio_details"
  get "/pricing", to: "static_page#pricing"
  get "/blog", to: "static_page#blog"
  get "/blog-single", to: "static_page#blog_single"
  get "/contact", to: "static_page#contact"

  resources :posts, only: [:index, :show] do
    collection do
      get "tags/:tag_id", to: "posts#tags"
    end
  end

  # AdminLTE
  namespace "admin" do
    root "static_page#root"
    get "/general_form", to: "static_page#general_form"
    get "/validation", to: "static_page#validation"
    get "/profile", to: "static_page#profile"
    get "/login", to: "static_page#login"

    resources :posts do
      collection do
        get "/org_new", to: "posts#org_new"
        post "/org_save", to: "posts#org_save"
      end
    end
    resources :sites
    resources :tags
  end
end

app/views/layouts/sailor/_breadcrumbs.html.erb
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2><%= breadcrumbs.last[0] %></h2>
      <ol>
        <% breadcrumbs.each do |breadcrumb| %>
          <% if (breadcrumb[1].nil?) %>
            <li><%= breadcrumb[0] %></li>
          <% else %>
            <li><%= link_to breadcrumb[0], breadcrumb[1] %></li>
          <% end %>
        <% end %>
      </ol>
    </div>

  </div>
</section><!-- End Breadcrumbs -->

app/views/layouts/sailor/_footer.html.erb
<!-- ======= Footer ======= -->
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <!--
      <div class="row">

        <div class="col-lg-3 col-md-6">
          <div class="footer-info">
            <h3>Sailor</h3>
            <p>
              A108 Adam Street <br>
              NY 535022, USA<br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>
        </div>

        <div class="col-lg-2 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-6 footer-newsletter">
          <h4>Our Newsletter</h4>
          <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          <form action="" method="post">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form>

        </div>

      </div>
    </div>
    -->
  </div>

  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong><span><%= @site.name %></span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/sailor-free-bootstrap-theme/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </div>
</footer><!-- End Footer -->

app/views/layouts/sailor/_header.html.erb
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container d-flex align-items-center">

    <h1 class="logo me-auto"><a href="/"><%= @site.name %></a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->
    <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

    <nav id="navbar" class="navbar">
      <ul>
        <li><%= link_to "Home", root_path, class: @menu == :home ? "active" : nil %></li>

        <li><%= link_to "About", about_path, class: @menu == :about ? "active" : nil %></li>
        <!--
        <li class="dropdown"><a href="#"><span>About</span> <i class="bi bi-chevron-down"></i></a>
          <ul>
            <li><%= link_to "About", about_path, class: @menu == :about ? "active" : nil %></li>
            <li><%= link_to "Team", team_path, class: @menu == :team ? "active" : nil %></li>
            <li><%= link_to "Testimonials", testimonials_path, class: @menu == :testimonials ? "active" : nil %></li>

            <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="#">Deep Drop Down 1</a></li>
                <li><a href="#">Deep Drop Down 2</a></li>
                <li><a href="#">Deep Drop Down 3</a></li>
                <li><a href="#">Deep Drop Down 4</a></li>
                <li><a href="#">Deep Drop Down 5</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li><%= link_to "Services", services_path, class: @menu == :services ? "active" : nil %></li>
        <li><%= link_to "Portfolio", portfolio_path, class: @menu == :portfolio ? "active" : nil %></li>
        <li><%= link_to "Pricing", pricing_path, class: @menu == :pricing ? "active" : nil %></li>
        <li><%= link_to "Blog", posts_path, class: @menu == :blog ? "active" : nil %></li>
        -->

        <li><%= link_to "Contact", contact_path, class: @menu == :contact ? "active" : nil %></li>
        <!--<li><a href="/" class="getstarted">Get Started</a></li>-->
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

  </div>
</header><!-- End Header -->

app/views/layouts/sailor/_hero.html.erb
<!-- ======= Hero Section ======= -->
<section id="hero">
  <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

    <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

    <div class="carousel-inner" role="listbox">

      <!-- Slide 1 -->
      <div class="carousel-item active" style="background-image: url(assets/img/slide/slide-1.jpg)">
        <div class="carousel-container">
          <div class="container">
            <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Sailor</span></h2>
            <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
            <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
          </div>
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item" style="background-image: url(assets/img/slide/slide-2.jpg)">
        <div class="carousel-container">
          <div class="container">
            <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
            <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
            <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
          </div>
        </div>
      </div>

      <!-- Slide 3 -->
      <div class="carousel-item" style="background-image: url(assets/img/slide/slide-3.jpg)">
        <div class="carousel-container">
          <div class="container">
            <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
            <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
            <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
          </div>
        </div>
      </div>

    </div>

    <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
    </a>

    <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
    </a>

  </div>
</section><!-- End Hero -->

app/views/layouts/sailor/application_base.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
    <%= content_for(:title) ? yield(:title) + " - " : "" %><%= @site.name %>
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Favicons -->
  <link href="/assets/sailor/img/favicon.png" rel="icon">
  <link href="/assets/sailor/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/assets/sailor/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="/assets/sailor/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/sailor/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/assets/sailor/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/assets/sailor/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/assets/sailor/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/assets/sailor/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/assets/sailor/css/style.css" rel="stylesheet">

  <%= stylesheet_link_tag "application" %>

  <!-- =======================================================
  * Template Name: Sailor
  * Template URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/
  * Updated: Mar 17 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

  <%= render "layouts/analytics" %>
</head>

<body>

  <%= yield :header %>

  <%= yield :hero %>

  <main id="main">

    <%= yield %>

  </main><!-- End #main -->

  <%= yield :footer %>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/assets/sailor/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/assets/sailor/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/assets/sailor/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/assets/sailor/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/assets/sailor/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="/assets/sailor/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/assets/sailor/js/main.js"></script>

  <%= javascript_importmap_tags %>

</body>

</html>